### ISSUE TITLE
Have you announced this at all on the FreeCAD forum ?

### ISSUE THREAD

**Issue by luzpaz** [Ediforce44/FreeCAD-Assembly4-BOM#1]
This looks awesome!

**Comment by Ediforce44** [comment]
Not so far, because I haven't seen too much people using FreeCAD for woodworking or something similar. But maybe it is a good idea to post it, because the YT video got some clicks. So maybe it is interesting for some more people.

**Comment by luzpaz** [comment]
Thanks! 
https://forum.freecadweb.org/viewtopic.php?f=20&t=72415  (Please add it to the README.md file)
